# Whether or not to ignore hidden files from the counter
ignore-hidden: true
# The amount of characters/bytes to read from a file per iteration until the
# end of the file. Increasing this value may speed up the counting process at
# the price of memory usage for storing the blocks.
block-size: 131072
# A block of language definitions based on extension that defines the name of
# the language, as well as its comment styles, any of these can be omitted
# aside from the extensions and language fields.
languages:
  -
    extensions: [ 'c', 'cpp', 'cxx', 'cc', 'C' ]
    language: C/C++ Source
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'h', 'hpp', 'hxx', 'hh', 'H' ]
    language: C/C++ Header
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'py' ]
    language: Python
    line-comment: '#'
  -
    extensions: [ 'java' ]
    language: Java
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'kt', 'kts' ]
    language: Kotlin
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'rs' ]
    language: Rust
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'js' ]
    language: JavaScript
    line-comment: /
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'css' ]
    language: CSS
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'html' ]
    language: HTML
    block-comment-begin: <!--
    block-comment-end: -->
  -
    extensions: [ 'ts', 'tsx' ]
    language: TypeScript
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'rb' ]
    language: Ruby
    line-comment: \#
  -
    extensions: [ 'lua' ]
    language: Lua
    line-comment: --
    block-comment-begin: --[[
    block-comment-end: --]]
  -
    extensions: [ 'd' ]
    language: D
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'cs' ]
    language: C#
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'php', 'php3', 'php4', 'php5' ]
    language: PHP
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'json' ]
    language: JSON
  -
    extensions: [ 'go' ]
    language: Go
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'swift' ]
    language: Swift
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'h', 'm', 'mm', 'M' ]
    language: Objective C
    line-comment: //
    block-comment-begin: /*
    block-comment-end: '*/'
  -
    extensions: [ 'yml', 'yaml' ]
    language: YAML
    line-comment: '#'
  -
    extensions: [ 'ini' ]
    language: INI Configuration
    line-comment: ;
# Ignore the non-main source directories for accurate counting
ignore:
  - yaml-cpp/
  - CMake/
  - build/
  - fmt/
  - .vscode/
  - LICENSE
  - README.md
  - CMakeLists.txt